using System.Reflection;

[assembly: Obfuscation(Feature = "Apply to type *: apply to member * when method or constructor: virtualization", Exclude = false)]
[assembly: Obfuscation(Feature = "type renaming pattern 'オマンコの難読化を解除しようとするのをやめる'.*", Exclude = false)]
[assembly: Obfuscation(Feature = "debug", Exclude = false)]
[assembly: Obfuscation(Feature = "encrypt resources", Exclude = false)]
[assembly: Obfuscation(Feature = "encrypt symbol names with password Nihon[3.0]", Exclude = false)]
[assembly: Obfuscation(Feature = "rename symbol names with printable characters", Exclude = false)]
[assembly: Obfuscation(Feature = "Apply to type *Impl: type renaming pattern '[_Nihon_]'.*", Exclude = false)]
[assembly: Obfuscation(Feature = "anonymous type properties renaming", Exclude = true)]
[assembly: Obfuscation(Feature = "design-time usage protection", Exclude = false)]
[assembly: Obfuscation(Feature = "string encryption", Exclude = false)]
[assembly: Obfuscation(Feature = "code control flow obfuscation", Exclude = false)]

[assembly: Obfuscation(Feature = "embed Microsoft.Web.WebView2.Core.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed Microsoft.Web.WebView2.WinForms.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed Microsoft.Web.WebView2.Wpf.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed WebView2Loader.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed Newtonsoft.Json.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed BouncyCastle.Crypto.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed DiscordRPC.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed websocket-sharp.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed Octokit.dll", Exclude = false)]
[assembly: Obfuscation(Feature = "embed Firebase.Auth.dll", Exclude = false)]
